# Generated by Django 4.0.4 on 2022-06-07 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox_1', models.CharField(default='unchecked', max_length=10)),
                ('checkbox_2', models.CharField(default='unchecked', max_length=10)),
                ('checkbox_3', models.CharField(default='unchecked', max_length=10)),
                ('checkbox_created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('checkbox_updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Grocery',
            },
        ),
    ]
