# Generated by Django 4.0.4 on 2022-06-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox_1', models.CharField(default='unchecked', max_length=10)),
                ('checkbox_2', models.CharField(default='unchecked', max_length=10)),
                ('checkbox_3', models.CharField(default='unchecked', max_length=10)),
            ],
        ),
    ]
