# Generated by Django 4.0.4 on 2022-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housework',
            name='bought_items',
            field=models.BooleanField(blank=True, null=True, verbose_name='買ったもの'),
        ),
    ]
