# Generated by Django 4.0.4 on 2022-05-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0002_housework_bought_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=10, null=True, verbose_name='商品')),
            ],
        ),
        migrations.AddField(
            model_name='housework',
            name='purchases',
            field=models.ManyToManyField(to='housework.purchases', verbose_name='買った物'),
        ),
    ]
