# Generated by Django 4.0.4 on 2022-05-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0002_housework_bought_items_alter_housework_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housework',
            name='update_at',
        ),
    ]
