# Generated by Django 4.0.4 on 2022-05-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0003_purchases_housework_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='item',
            new_name='my_purchases',
        ),
    ]
