# Generated by Django 4.0.4 on 2022-05-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0004_rename_item_purchases_my_purchases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housework',
            old_name='purchases',
            new_name='what_i_bought',
        ),
    ]
